{{ with .Values.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluentd_kubernetes.fullname" $ }}
  labels:
    app: {{ template "fluentd_kubernetes.name" $ }}
    chart: {{ template "fluentd_kubernetes.chart" $ }}
type: Opaque
data:
  {{- range $name, $value := . }}
  {{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
